version: '3'

services:
  pgsql:
    image: postgres:latest
    ports:
      - '3500:5432'
    container_name: 'slotcar-pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  api-logs:
  pg-data:
